### ISSUE TITLE
TypeError: Multiple inheritance with NamedTuple is not supported

### ISSUE THREAD

**Issue by Aryavir07** [BSI-Bocconi/bsi-sentiment#3]
File "C:\Users\dell\anaconda3\lib\typing.py", line 1901, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported

**Comment by stefanocortinovis** [comment]
I've just release a new version of the package on PyPI. Could you update it and let me know if the error above persists?

**Comment by Aryavir07** [comment]
@scortino thanks! it is working now.
